// Code generated by ent, DO NOT EDIT.

package paymentrequisite

import (
	"gym-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldID, id))
}

// BankKard1 applies equality check predicate on the "bank_kard_1" field. It's identical to BankKard1EQ.
func BankKard1(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard1, v))
}

// BankKard2 applies equality check predicate on the "bank_kard_2" field. It's identical to BankKard2EQ.
func BankKard2(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard2, v))
}

// BankKard3 applies equality check predicate on the "bank_kard_3" field. It's identical to BankKard3EQ.
func BankKard3(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard3, v))
}

// BankKard4 applies equality check predicate on the "bank_kard_4" field. It's identical to BankKard4EQ.
func BankKard4(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard4, v))
}

// BankKard5 applies equality check predicate on the "bank_kard_5" field. It's identical to BankKard5EQ.
func BankKard5(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard5, v))
}

// NameBankKard1 applies equality check predicate on the "name_bank_kard_1" field. It's identical to NameBankKard1EQ.
func NameBankKard1(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard1, v))
}

// NameBankKard2 applies equality check predicate on the "name_bank_kard_2" field. It's identical to NameBankKard2EQ.
func NameBankKard2(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard2, v))
}

// NameBankKard3 applies equality check predicate on the "name_bank_kard_3" field. It's identical to NameBankKard3EQ.
func NameBankKard3(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard3, v))
}

// NameBankKard4 applies equality check predicate on the "name_bank_kard_4" field. It's identical to NameBankKard4EQ.
func NameBankKard4(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard4, v))
}

// NameBankKard5 applies equality check predicate on the "name_bank_kard_5" field. It's identical to NameBankKard5EQ.
func NameBankKard5(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard5, v))
}

// NameBank applies equality check predicate on the "name_bank" field. It's identical to NameBankEQ.
func NameBank(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBank, v))
}

// Iban applies equality check predicate on the "iban" field. It's identical to IbanEQ.
func Iban(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldIban, v))
}

// Edrpou applies equality check predicate on the "edrpou" field. It's identical to EdrpouEQ.
func Edrpou(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldEdrpou, v))
}

// ReceiverName applies equality check predicate on the "receiver_name" field. It's identical to ReceiverNameEQ.
func ReceiverName(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldReceiverName, v))
}

// PaymentPurpose applies equality check predicate on the "payment_purpose" field. It's identical to PaymentPurposeEQ.
func PaymentPurpose(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldPaymentPurpose, v))
}

// Mfo applies equality check predicate on the "mfo" field. It's identical to MfoEQ.
func Mfo(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldMfo, v))
}

// AccountNumber applies equality check predicate on the "account_number" field. It's identical to AccountNumberEQ.
func AccountNumber(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldAccountNumber, v))
}

// BankKard1EQ applies the EQ predicate on the "bank_kard_1" field.
func BankKard1EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard1, v))
}

// BankKard1NEQ applies the NEQ predicate on the "bank_kard_1" field.
func BankKard1NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldBankKard1, v))
}

// BankKard1In applies the In predicate on the "bank_kard_1" field.
func BankKard1In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldBankKard1, vs...))
}

// BankKard1NotIn applies the NotIn predicate on the "bank_kard_1" field.
func BankKard1NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldBankKard1, vs...))
}

// BankKard1GT applies the GT predicate on the "bank_kard_1" field.
func BankKard1GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldBankKard1, v))
}

// BankKard1GTE applies the GTE predicate on the "bank_kard_1" field.
func BankKard1GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldBankKard1, v))
}

// BankKard1LT applies the LT predicate on the "bank_kard_1" field.
func BankKard1LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldBankKard1, v))
}

// BankKard1LTE applies the LTE predicate on the "bank_kard_1" field.
func BankKard1LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldBankKard1, v))
}

// BankKard1Contains applies the Contains predicate on the "bank_kard_1" field.
func BankKard1Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldBankKard1, v))
}

// BankKard1HasPrefix applies the HasPrefix predicate on the "bank_kard_1" field.
func BankKard1HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldBankKard1, v))
}

// BankKard1HasSuffix applies the HasSuffix predicate on the "bank_kard_1" field.
func BankKard1HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldBankKard1, v))
}

// BankKard1IsNil applies the IsNil predicate on the "bank_kard_1" field.
func BankKard1IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldBankKard1))
}

// BankKard1NotNil applies the NotNil predicate on the "bank_kard_1" field.
func BankKard1NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldBankKard1))
}

// BankKard1EqualFold applies the EqualFold predicate on the "bank_kard_1" field.
func BankKard1EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldBankKard1, v))
}

// BankKard1ContainsFold applies the ContainsFold predicate on the "bank_kard_1" field.
func BankKard1ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldBankKard1, v))
}

// BankKard2EQ applies the EQ predicate on the "bank_kard_2" field.
func BankKard2EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard2, v))
}

// BankKard2NEQ applies the NEQ predicate on the "bank_kard_2" field.
func BankKard2NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldBankKard2, v))
}

// BankKard2In applies the In predicate on the "bank_kard_2" field.
func BankKard2In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldBankKard2, vs...))
}

// BankKard2NotIn applies the NotIn predicate on the "bank_kard_2" field.
func BankKard2NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldBankKard2, vs...))
}

// BankKard2GT applies the GT predicate on the "bank_kard_2" field.
func BankKard2GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldBankKard2, v))
}

// BankKard2GTE applies the GTE predicate on the "bank_kard_2" field.
func BankKard2GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldBankKard2, v))
}

// BankKard2LT applies the LT predicate on the "bank_kard_2" field.
func BankKard2LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldBankKard2, v))
}

// BankKard2LTE applies the LTE predicate on the "bank_kard_2" field.
func BankKard2LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldBankKard2, v))
}

// BankKard2Contains applies the Contains predicate on the "bank_kard_2" field.
func BankKard2Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldBankKard2, v))
}

// BankKard2HasPrefix applies the HasPrefix predicate on the "bank_kard_2" field.
func BankKard2HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldBankKard2, v))
}

// BankKard2HasSuffix applies the HasSuffix predicate on the "bank_kard_2" field.
func BankKard2HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldBankKard2, v))
}

// BankKard2IsNil applies the IsNil predicate on the "bank_kard_2" field.
func BankKard2IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldBankKard2))
}

// BankKard2NotNil applies the NotNil predicate on the "bank_kard_2" field.
func BankKard2NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldBankKard2))
}

// BankKard2EqualFold applies the EqualFold predicate on the "bank_kard_2" field.
func BankKard2EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldBankKard2, v))
}

// BankKard2ContainsFold applies the ContainsFold predicate on the "bank_kard_2" field.
func BankKard2ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldBankKard2, v))
}

// BankKard3EQ applies the EQ predicate on the "bank_kard_3" field.
func BankKard3EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard3, v))
}

// BankKard3NEQ applies the NEQ predicate on the "bank_kard_3" field.
func BankKard3NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldBankKard3, v))
}

// BankKard3In applies the In predicate on the "bank_kard_3" field.
func BankKard3In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldBankKard3, vs...))
}

// BankKard3NotIn applies the NotIn predicate on the "bank_kard_3" field.
func BankKard3NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldBankKard3, vs...))
}

// BankKard3GT applies the GT predicate on the "bank_kard_3" field.
func BankKard3GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldBankKard3, v))
}

// BankKard3GTE applies the GTE predicate on the "bank_kard_3" field.
func BankKard3GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldBankKard3, v))
}

// BankKard3LT applies the LT predicate on the "bank_kard_3" field.
func BankKard3LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldBankKard3, v))
}

// BankKard3LTE applies the LTE predicate on the "bank_kard_3" field.
func BankKard3LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldBankKard3, v))
}

// BankKard3Contains applies the Contains predicate on the "bank_kard_3" field.
func BankKard3Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldBankKard3, v))
}

// BankKard3HasPrefix applies the HasPrefix predicate on the "bank_kard_3" field.
func BankKard3HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldBankKard3, v))
}

// BankKard3HasSuffix applies the HasSuffix predicate on the "bank_kard_3" field.
func BankKard3HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldBankKard3, v))
}

// BankKard3IsNil applies the IsNil predicate on the "bank_kard_3" field.
func BankKard3IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldBankKard3))
}

// BankKard3NotNil applies the NotNil predicate on the "bank_kard_3" field.
func BankKard3NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldBankKard3))
}

// BankKard3EqualFold applies the EqualFold predicate on the "bank_kard_3" field.
func BankKard3EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldBankKard3, v))
}

// BankKard3ContainsFold applies the ContainsFold predicate on the "bank_kard_3" field.
func BankKard3ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldBankKard3, v))
}

// BankKard4EQ applies the EQ predicate on the "bank_kard_4" field.
func BankKard4EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard4, v))
}

// BankKard4NEQ applies the NEQ predicate on the "bank_kard_4" field.
func BankKard4NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldBankKard4, v))
}

// BankKard4In applies the In predicate on the "bank_kard_4" field.
func BankKard4In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldBankKard4, vs...))
}

// BankKard4NotIn applies the NotIn predicate on the "bank_kard_4" field.
func BankKard4NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldBankKard4, vs...))
}

// BankKard4GT applies the GT predicate on the "bank_kard_4" field.
func BankKard4GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldBankKard4, v))
}

// BankKard4GTE applies the GTE predicate on the "bank_kard_4" field.
func BankKard4GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldBankKard4, v))
}

// BankKard4LT applies the LT predicate on the "bank_kard_4" field.
func BankKard4LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldBankKard4, v))
}

// BankKard4LTE applies the LTE predicate on the "bank_kard_4" field.
func BankKard4LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldBankKard4, v))
}

// BankKard4Contains applies the Contains predicate on the "bank_kard_4" field.
func BankKard4Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldBankKard4, v))
}

// BankKard4HasPrefix applies the HasPrefix predicate on the "bank_kard_4" field.
func BankKard4HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldBankKard4, v))
}

// BankKard4HasSuffix applies the HasSuffix predicate on the "bank_kard_4" field.
func BankKard4HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldBankKard4, v))
}

// BankKard4IsNil applies the IsNil predicate on the "bank_kard_4" field.
func BankKard4IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldBankKard4))
}

// BankKard4NotNil applies the NotNil predicate on the "bank_kard_4" field.
func BankKard4NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldBankKard4))
}

// BankKard4EqualFold applies the EqualFold predicate on the "bank_kard_4" field.
func BankKard4EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldBankKard4, v))
}

// BankKard4ContainsFold applies the ContainsFold predicate on the "bank_kard_4" field.
func BankKard4ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldBankKard4, v))
}

// BankKard5EQ applies the EQ predicate on the "bank_kard_5" field.
func BankKard5EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldBankKard5, v))
}

// BankKard5NEQ applies the NEQ predicate on the "bank_kard_5" field.
func BankKard5NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldBankKard5, v))
}

// BankKard5In applies the In predicate on the "bank_kard_5" field.
func BankKard5In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldBankKard5, vs...))
}

// BankKard5NotIn applies the NotIn predicate on the "bank_kard_5" field.
func BankKard5NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldBankKard5, vs...))
}

// BankKard5GT applies the GT predicate on the "bank_kard_5" field.
func BankKard5GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldBankKard5, v))
}

// BankKard5GTE applies the GTE predicate on the "bank_kard_5" field.
func BankKard5GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldBankKard5, v))
}

// BankKard5LT applies the LT predicate on the "bank_kard_5" field.
func BankKard5LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldBankKard5, v))
}

// BankKard5LTE applies the LTE predicate on the "bank_kard_5" field.
func BankKard5LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldBankKard5, v))
}

// BankKard5Contains applies the Contains predicate on the "bank_kard_5" field.
func BankKard5Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldBankKard5, v))
}

// BankKard5HasPrefix applies the HasPrefix predicate on the "bank_kard_5" field.
func BankKard5HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldBankKard5, v))
}

// BankKard5HasSuffix applies the HasSuffix predicate on the "bank_kard_5" field.
func BankKard5HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldBankKard5, v))
}

// BankKard5IsNil applies the IsNil predicate on the "bank_kard_5" field.
func BankKard5IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldBankKard5))
}

// BankKard5NotNil applies the NotNil predicate on the "bank_kard_5" field.
func BankKard5NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldBankKard5))
}

// BankKard5EqualFold applies the EqualFold predicate on the "bank_kard_5" field.
func BankKard5EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldBankKard5, v))
}

// BankKard5ContainsFold applies the ContainsFold predicate on the "bank_kard_5" field.
func BankKard5ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldBankKard5, v))
}

// NameBankKard1EQ applies the EQ predicate on the "name_bank_kard_1" field.
func NameBankKard1EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard1, v))
}

// NameBankKard1NEQ applies the NEQ predicate on the "name_bank_kard_1" field.
func NameBankKard1NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldNameBankKard1, v))
}

// NameBankKard1In applies the In predicate on the "name_bank_kard_1" field.
func NameBankKard1In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldNameBankKard1, vs...))
}

// NameBankKard1NotIn applies the NotIn predicate on the "name_bank_kard_1" field.
func NameBankKard1NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldNameBankKard1, vs...))
}

// NameBankKard1GT applies the GT predicate on the "name_bank_kard_1" field.
func NameBankKard1GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldNameBankKard1, v))
}

// NameBankKard1GTE applies the GTE predicate on the "name_bank_kard_1" field.
func NameBankKard1GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldNameBankKard1, v))
}

// NameBankKard1LT applies the LT predicate on the "name_bank_kard_1" field.
func NameBankKard1LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldNameBankKard1, v))
}

// NameBankKard1LTE applies the LTE predicate on the "name_bank_kard_1" field.
func NameBankKard1LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldNameBankKard1, v))
}

// NameBankKard1Contains applies the Contains predicate on the "name_bank_kard_1" field.
func NameBankKard1Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldNameBankKard1, v))
}

// NameBankKard1HasPrefix applies the HasPrefix predicate on the "name_bank_kard_1" field.
func NameBankKard1HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldNameBankKard1, v))
}

// NameBankKard1HasSuffix applies the HasSuffix predicate on the "name_bank_kard_1" field.
func NameBankKard1HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldNameBankKard1, v))
}

// NameBankKard1IsNil applies the IsNil predicate on the "name_bank_kard_1" field.
func NameBankKard1IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldNameBankKard1))
}

// NameBankKard1NotNil applies the NotNil predicate on the "name_bank_kard_1" field.
func NameBankKard1NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldNameBankKard1))
}

// NameBankKard1EqualFold applies the EqualFold predicate on the "name_bank_kard_1" field.
func NameBankKard1EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldNameBankKard1, v))
}

// NameBankKard1ContainsFold applies the ContainsFold predicate on the "name_bank_kard_1" field.
func NameBankKard1ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldNameBankKard1, v))
}

// NameBankKard2EQ applies the EQ predicate on the "name_bank_kard_2" field.
func NameBankKard2EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard2, v))
}

// NameBankKard2NEQ applies the NEQ predicate on the "name_bank_kard_2" field.
func NameBankKard2NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldNameBankKard2, v))
}

// NameBankKard2In applies the In predicate on the "name_bank_kard_2" field.
func NameBankKard2In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldNameBankKard2, vs...))
}

// NameBankKard2NotIn applies the NotIn predicate on the "name_bank_kard_2" field.
func NameBankKard2NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldNameBankKard2, vs...))
}

// NameBankKard2GT applies the GT predicate on the "name_bank_kard_2" field.
func NameBankKard2GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldNameBankKard2, v))
}

// NameBankKard2GTE applies the GTE predicate on the "name_bank_kard_2" field.
func NameBankKard2GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldNameBankKard2, v))
}

// NameBankKard2LT applies the LT predicate on the "name_bank_kard_2" field.
func NameBankKard2LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldNameBankKard2, v))
}

// NameBankKard2LTE applies the LTE predicate on the "name_bank_kard_2" field.
func NameBankKard2LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldNameBankKard2, v))
}

// NameBankKard2Contains applies the Contains predicate on the "name_bank_kard_2" field.
func NameBankKard2Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldNameBankKard2, v))
}

// NameBankKard2HasPrefix applies the HasPrefix predicate on the "name_bank_kard_2" field.
func NameBankKard2HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldNameBankKard2, v))
}

// NameBankKard2HasSuffix applies the HasSuffix predicate on the "name_bank_kard_2" field.
func NameBankKard2HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldNameBankKard2, v))
}

// NameBankKard2IsNil applies the IsNil predicate on the "name_bank_kard_2" field.
func NameBankKard2IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldNameBankKard2))
}

// NameBankKard2NotNil applies the NotNil predicate on the "name_bank_kard_2" field.
func NameBankKard2NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldNameBankKard2))
}

// NameBankKard2EqualFold applies the EqualFold predicate on the "name_bank_kard_2" field.
func NameBankKard2EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldNameBankKard2, v))
}

// NameBankKard2ContainsFold applies the ContainsFold predicate on the "name_bank_kard_2" field.
func NameBankKard2ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldNameBankKard2, v))
}

// NameBankKard3EQ applies the EQ predicate on the "name_bank_kard_3" field.
func NameBankKard3EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard3, v))
}

// NameBankKard3NEQ applies the NEQ predicate on the "name_bank_kard_3" field.
func NameBankKard3NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldNameBankKard3, v))
}

// NameBankKard3In applies the In predicate on the "name_bank_kard_3" field.
func NameBankKard3In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldNameBankKard3, vs...))
}

// NameBankKard3NotIn applies the NotIn predicate on the "name_bank_kard_3" field.
func NameBankKard3NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldNameBankKard3, vs...))
}

// NameBankKard3GT applies the GT predicate on the "name_bank_kard_3" field.
func NameBankKard3GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldNameBankKard3, v))
}

// NameBankKard3GTE applies the GTE predicate on the "name_bank_kard_3" field.
func NameBankKard3GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldNameBankKard3, v))
}

// NameBankKard3LT applies the LT predicate on the "name_bank_kard_3" field.
func NameBankKard3LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldNameBankKard3, v))
}

// NameBankKard3LTE applies the LTE predicate on the "name_bank_kard_3" field.
func NameBankKard3LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldNameBankKard3, v))
}

// NameBankKard3Contains applies the Contains predicate on the "name_bank_kard_3" field.
func NameBankKard3Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldNameBankKard3, v))
}

// NameBankKard3HasPrefix applies the HasPrefix predicate on the "name_bank_kard_3" field.
func NameBankKard3HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldNameBankKard3, v))
}

// NameBankKard3HasSuffix applies the HasSuffix predicate on the "name_bank_kard_3" field.
func NameBankKard3HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldNameBankKard3, v))
}

// NameBankKard3IsNil applies the IsNil predicate on the "name_bank_kard_3" field.
func NameBankKard3IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldNameBankKard3))
}

// NameBankKard3NotNil applies the NotNil predicate on the "name_bank_kard_3" field.
func NameBankKard3NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldNameBankKard3))
}

// NameBankKard3EqualFold applies the EqualFold predicate on the "name_bank_kard_3" field.
func NameBankKard3EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldNameBankKard3, v))
}

// NameBankKard3ContainsFold applies the ContainsFold predicate on the "name_bank_kard_3" field.
func NameBankKard3ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldNameBankKard3, v))
}

// NameBankKard4EQ applies the EQ predicate on the "name_bank_kard_4" field.
func NameBankKard4EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard4, v))
}

// NameBankKard4NEQ applies the NEQ predicate on the "name_bank_kard_4" field.
func NameBankKard4NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldNameBankKard4, v))
}

// NameBankKard4In applies the In predicate on the "name_bank_kard_4" field.
func NameBankKard4In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldNameBankKard4, vs...))
}

// NameBankKard4NotIn applies the NotIn predicate on the "name_bank_kard_4" field.
func NameBankKard4NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldNameBankKard4, vs...))
}

// NameBankKard4GT applies the GT predicate on the "name_bank_kard_4" field.
func NameBankKard4GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldNameBankKard4, v))
}

// NameBankKard4GTE applies the GTE predicate on the "name_bank_kard_4" field.
func NameBankKard4GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldNameBankKard4, v))
}

// NameBankKard4LT applies the LT predicate on the "name_bank_kard_4" field.
func NameBankKard4LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldNameBankKard4, v))
}

// NameBankKard4LTE applies the LTE predicate on the "name_bank_kard_4" field.
func NameBankKard4LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldNameBankKard4, v))
}

// NameBankKard4Contains applies the Contains predicate on the "name_bank_kard_4" field.
func NameBankKard4Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldNameBankKard4, v))
}

// NameBankKard4HasPrefix applies the HasPrefix predicate on the "name_bank_kard_4" field.
func NameBankKard4HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldNameBankKard4, v))
}

// NameBankKard4HasSuffix applies the HasSuffix predicate on the "name_bank_kard_4" field.
func NameBankKard4HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldNameBankKard4, v))
}

// NameBankKard4IsNil applies the IsNil predicate on the "name_bank_kard_4" field.
func NameBankKard4IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldNameBankKard4))
}

// NameBankKard4NotNil applies the NotNil predicate on the "name_bank_kard_4" field.
func NameBankKard4NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldNameBankKard4))
}

// NameBankKard4EqualFold applies the EqualFold predicate on the "name_bank_kard_4" field.
func NameBankKard4EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldNameBankKard4, v))
}

// NameBankKard4ContainsFold applies the ContainsFold predicate on the "name_bank_kard_4" field.
func NameBankKard4ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldNameBankKard4, v))
}

// NameBankKard5EQ applies the EQ predicate on the "name_bank_kard_5" field.
func NameBankKard5EQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBankKard5, v))
}

// NameBankKard5NEQ applies the NEQ predicate on the "name_bank_kard_5" field.
func NameBankKard5NEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldNameBankKard5, v))
}

// NameBankKard5In applies the In predicate on the "name_bank_kard_5" field.
func NameBankKard5In(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldNameBankKard5, vs...))
}

// NameBankKard5NotIn applies the NotIn predicate on the "name_bank_kard_5" field.
func NameBankKard5NotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldNameBankKard5, vs...))
}

// NameBankKard5GT applies the GT predicate on the "name_bank_kard_5" field.
func NameBankKard5GT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldNameBankKard5, v))
}

// NameBankKard5GTE applies the GTE predicate on the "name_bank_kard_5" field.
func NameBankKard5GTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldNameBankKard5, v))
}

// NameBankKard5LT applies the LT predicate on the "name_bank_kard_5" field.
func NameBankKard5LT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldNameBankKard5, v))
}

// NameBankKard5LTE applies the LTE predicate on the "name_bank_kard_5" field.
func NameBankKard5LTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldNameBankKard5, v))
}

// NameBankKard5Contains applies the Contains predicate on the "name_bank_kard_5" field.
func NameBankKard5Contains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldNameBankKard5, v))
}

// NameBankKard5HasPrefix applies the HasPrefix predicate on the "name_bank_kard_5" field.
func NameBankKard5HasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldNameBankKard5, v))
}

// NameBankKard5HasSuffix applies the HasSuffix predicate on the "name_bank_kard_5" field.
func NameBankKard5HasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldNameBankKard5, v))
}

// NameBankKard5IsNil applies the IsNil predicate on the "name_bank_kard_5" field.
func NameBankKard5IsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldNameBankKard5))
}

// NameBankKard5NotNil applies the NotNil predicate on the "name_bank_kard_5" field.
func NameBankKard5NotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldNameBankKard5))
}

// NameBankKard5EqualFold applies the EqualFold predicate on the "name_bank_kard_5" field.
func NameBankKard5EqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldNameBankKard5, v))
}

// NameBankKard5ContainsFold applies the ContainsFold predicate on the "name_bank_kard_5" field.
func NameBankKard5ContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldNameBankKard5, v))
}

// NameBankEQ applies the EQ predicate on the "name_bank" field.
func NameBankEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldNameBank, v))
}

// NameBankNEQ applies the NEQ predicate on the "name_bank" field.
func NameBankNEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldNameBank, v))
}

// NameBankIn applies the In predicate on the "name_bank" field.
func NameBankIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldNameBank, vs...))
}

// NameBankNotIn applies the NotIn predicate on the "name_bank" field.
func NameBankNotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldNameBank, vs...))
}

// NameBankGT applies the GT predicate on the "name_bank" field.
func NameBankGT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldNameBank, v))
}

// NameBankGTE applies the GTE predicate on the "name_bank" field.
func NameBankGTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldNameBank, v))
}

// NameBankLT applies the LT predicate on the "name_bank" field.
func NameBankLT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldNameBank, v))
}

// NameBankLTE applies the LTE predicate on the "name_bank" field.
func NameBankLTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldNameBank, v))
}

// NameBankContains applies the Contains predicate on the "name_bank" field.
func NameBankContains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldNameBank, v))
}

// NameBankHasPrefix applies the HasPrefix predicate on the "name_bank" field.
func NameBankHasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldNameBank, v))
}

// NameBankHasSuffix applies the HasSuffix predicate on the "name_bank" field.
func NameBankHasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldNameBank, v))
}

// NameBankIsNil applies the IsNil predicate on the "name_bank" field.
func NameBankIsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldNameBank))
}

// NameBankNotNil applies the NotNil predicate on the "name_bank" field.
func NameBankNotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldNameBank))
}

// NameBankEqualFold applies the EqualFold predicate on the "name_bank" field.
func NameBankEqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldNameBank, v))
}

// NameBankContainsFold applies the ContainsFold predicate on the "name_bank" field.
func NameBankContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldNameBank, v))
}

// IbanEQ applies the EQ predicate on the "iban" field.
func IbanEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldIban, v))
}

// IbanNEQ applies the NEQ predicate on the "iban" field.
func IbanNEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldIban, v))
}

// IbanIn applies the In predicate on the "iban" field.
func IbanIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldIban, vs...))
}

// IbanNotIn applies the NotIn predicate on the "iban" field.
func IbanNotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldIban, vs...))
}

// IbanGT applies the GT predicate on the "iban" field.
func IbanGT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldIban, v))
}

// IbanGTE applies the GTE predicate on the "iban" field.
func IbanGTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldIban, v))
}

// IbanLT applies the LT predicate on the "iban" field.
func IbanLT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldIban, v))
}

// IbanLTE applies the LTE predicate on the "iban" field.
func IbanLTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldIban, v))
}

// IbanContains applies the Contains predicate on the "iban" field.
func IbanContains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldIban, v))
}

// IbanHasPrefix applies the HasPrefix predicate on the "iban" field.
func IbanHasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldIban, v))
}

// IbanHasSuffix applies the HasSuffix predicate on the "iban" field.
func IbanHasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldIban, v))
}

// IbanIsNil applies the IsNil predicate on the "iban" field.
func IbanIsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldIban))
}

// IbanNotNil applies the NotNil predicate on the "iban" field.
func IbanNotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldIban))
}

// IbanEqualFold applies the EqualFold predicate on the "iban" field.
func IbanEqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldIban, v))
}

// IbanContainsFold applies the ContainsFold predicate on the "iban" field.
func IbanContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldIban, v))
}

// EdrpouEQ applies the EQ predicate on the "edrpou" field.
func EdrpouEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldEdrpou, v))
}

// EdrpouNEQ applies the NEQ predicate on the "edrpou" field.
func EdrpouNEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldEdrpou, v))
}

// EdrpouIn applies the In predicate on the "edrpou" field.
func EdrpouIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldEdrpou, vs...))
}

// EdrpouNotIn applies the NotIn predicate on the "edrpou" field.
func EdrpouNotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldEdrpou, vs...))
}

// EdrpouGT applies the GT predicate on the "edrpou" field.
func EdrpouGT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldEdrpou, v))
}

// EdrpouGTE applies the GTE predicate on the "edrpou" field.
func EdrpouGTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldEdrpou, v))
}

// EdrpouLT applies the LT predicate on the "edrpou" field.
func EdrpouLT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldEdrpou, v))
}

// EdrpouLTE applies the LTE predicate on the "edrpou" field.
func EdrpouLTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldEdrpou, v))
}

// EdrpouContains applies the Contains predicate on the "edrpou" field.
func EdrpouContains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldEdrpou, v))
}

// EdrpouHasPrefix applies the HasPrefix predicate on the "edrpou" field.
func EdrpouHasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldEdrpou, v))
}

// EdrpouHasSuffix applies the HasSuffix predicate on the "edrpou" field.
func EdrpouHasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldEdrpou, v))
}

// EdrpouIsNil applies the IsNil predicate on the "edrpou" field.
func EdrpouIsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldEdrpou))
}

// EdrpouNotNil applies the NotNil predicate on the "edrpou" field.
func EdrpouNotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldEdrpou))
}

// EdrpouEqualFold applies the EqualFold predicate on the "edrpou" field.
func EdrpouEqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldEdrpou, v))
}

// EdrpouContainsFold applies the ContainsFold predicate on the "edrpou" field.
func EdrpouContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldEdrpou, v))
}

// ReceiverNameEQ applies the EQ predicate on the "receiver_name" field.
func ReceiverNameEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldReceiverName, v))
}

// ReceiverNameNEQ applies the NEQ predicate on the "receiver_name" field.
func ReceiverNameNEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldReceiverName, v))
}

// ReceiverNameIn applies the In predicate on the "receiver_name" field.
func ReceiverNameIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldReceiverName, vs...))
}

// ReceiverNameNotIn applies the NotIn predicate on the "receiver_name" field.
func ReceiverNameNotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldReceiverName, vs...))
}

// ReceiverNameGT applies the GT predicate on the "receiver_name" field.
func ReceiverNameGT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldReceiverName, v))
}

// ReceiverNameGTE applies the GTE predicate on the "receiver_name" field.
func ReceiverNameGTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldReceiverName, v))
}

// ReceiverNameLT applies the LT predicate on the "receiver_name" field.
func ReceiverNameLT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldReceiverName, v))
}

// ReceiverNameLTE applies the LTE predicate on the "receiver_name" field.
func ReceiverNameLTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldReceiverName, v))
}

// ReceiverNameContains applies the Contains predicate on the "receiver_name" field.
func ReceiverNameContains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldReceiverName, v))
}

// ReceiverNameHasPrefix applies the HasPrefix predicate on the "receiver_name" field.
func ReceiverNameHasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldReceiverName, v))
}

// ReceiverNameHasSuffix applies the HasSuffix predicate on the "receiver_name" field.
func ReceiverNameHasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldReceiverName, v))
}

// ReceiverNameIsNil applies the IsNil predicate on the "receiver_name" field.
func ReceiverNameIsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldReceiverName))
}

// ReceiverNameNotNil applies the NotNil predicate on the "receiver_name" field.
func ReceiverNameNotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldReceiverName))
}

// ReceiverNameEqualFold applies the EqualFold predicate on the "receiver_name" field.
func ReceiverNameEqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldReceiverName, v))
}

// ReceiverNameContainsFold applies the ContainsFold predicate on the "receiver_name" field.
func ReceiverNameContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldReceiverName, v))
}

// PaymentPurposeEQ applies the EQ predicate on the "payment_purpose" field.
func PaymentPurposeEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldPaymentPurpose, v))
}

// PaymentPurposeNEQ applies the NEQ predicate on the "payment_purpose" field.
func PaymentPurposeNEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldPaymentPurpose, v))
}

// PaymentPurposeIn applies the In predicate on the "payment_purpose" field.
func PaymentPurposeIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldPaymentPurpose, vs...))
}

// PaymentPurposeNotIn applies the NotIn predicate on the "payment_purpose" field.
func PaymentPurposeNotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldPaymentPurpose, vs...))
}

// PaymentPurposeGT applies the GT predicate on the "payment_purpose" field.
func PaymentPurposeGT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldPaymentPurpose, v))
}

// PaymentPurposeGTE applies the GTE predicate on the "payment_purpose" field.
func PaymentPurposeGTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldPaymentPurpose, v))
}

// PaymentPurposeLT applies the LT predicate on the "payment_purpose" field.
func PaymentPurposeLT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldPaymentPurpose, v))
}

// PaymentPurposeLTE applies the LTE predicate on the "payment_purpose" field.
func PaymentPurposeLTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldPaymentPurpose, v))
}

// PaymentPurposeContains applies the Contains predicate on the "payment_purpose" field.
func PaymentPurposeContains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldPaymentPurpose, v))
}

// PaymentPurposeHasPrefix applies the HasPrefix predicate on the "payment_purpose" field.
func PaymentPurposeHasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldPaymentPurpose, v))
}

// PaymentPurposeHasSuffix applies the HasSuffix predicate on the "payment_purpose" field.
func PaymentPurposeHasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldPaymentPurpose, v))
}

// PaymentPurposeIsNil applies the IsNil predicate on the "payment_purpose" field.
func PaymentPurposeIsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldPaymentPurpose))
}

// PaymentPurposeNotNil applies the NotNil predicate on the "payment_purpose" field.
func PaymentPurposeNotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldPaymentPurpose))
}

// PaymentPurposeEqualFold applies the EqualFold predicate on the "payment_purpose" field.
func PaymentPurposeEqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldPaymentPurpose, v))
}

// PaymentPurposeContainsFold applies the ContainsFold predicate on the "payment_purpose" field.
func PaymentPurposeContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldPaymentPurpose, v))
}

// MfoEQ applies the EQ predicate on the "mfo" field.
func MfoEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldMfo, v))
}

// MfoNEQ applies the NEQ predicate on the "mfo" field.
func MfoNEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldMfo, v))
}

// MfoIn applies the In predicate on the "mfo" field.
func MfoIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldMfo, vs...))
}

// MfoNotIn applies the NotIn predicate on the "mfo" field.
func MfoNotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldMfo, vs...))
}

// MfoGT applies the GT predicate on the "mfo" field.
func MfoGT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldMfo, v))
}

// MfoGTE applies the GTE predicate on the "mfo" field.
func MfoGTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldMfo, v))
}

// MfoLT applies the LT predicate on the "mfo" field.
func MfoLT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldMfo, v))
}

// MfoLTE applies the LTE predicate on the "mfo" field.
func MfoLTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldMfo, v))
}

// MfoContains applies the Contains predicate on the "mfo" field.
func MfoContains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldMfo, v))
}

// MfoHasPrefix applies the HasPrefix predicate on the "mfo" field.
func MfoHasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldMfo, v))
}

// MfoHasSuffix applies the HasSuffix predicate on the "mfo" field.
func MfoHasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldMfo, v))
}

// MfoIsNil applies the IsNil predicate on the "mfo" field.
func MfoIsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldMfo))
}

// MfoNotNil applies the NotNil predicate on the "mfo" field.
func MfoNotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldMfo))
}

// MfoEqualFold applies the EqualFold predicate on the "mfo" field.
func MfoEqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldMfo, v))
}

// MfoContainsFold applies the ContainsFold predicate on the "mfo" field.
func MfoContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldMfo, v))
}

// AccountNumberEQ applies the EQ predicate on the "account_number" field.
func AccountNumberEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEQ(FieldAccountNumber, v))
}

// AccountNumberNEQ applies the NEQ predicate on the "account_number" field.
func AccountNumberNEQ(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNEQ(FieldAccountNumber, v))
}

// AccountNumberIn applies the In predicate on the "account_number" field.
func AccountNumberIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIn(FieldAccountNumber, vs...))
}

// AccountNumberNotIn applies the NotIn predicate on the "account_number" field.
func AccountNumberNotIn(vs ...string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotIn(FieldAccountNumber, vs...))
}

// AccountNumberGT applies the GT predicate on the "account_number" field.
func AccountNumberGT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGT(FieldAccountNumber, v))
}

// AccountNumberGTE applies the GTE predicate on the "account_number" field.
func AccountNumberGTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldGTE(FieldAccountNumber, v))
}

// AccountNumberLT applies the LT predicate on the "account_number" field.
func AccountNumberLT(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLT(FieldAccountNumber, v))
}

// AccountNumberLTE applies the LTE predicate on the "account_number" field.
func AccountNumberLTE(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldLTE(FieldAccountNumber, v))
}

// AccountNumberContains applies the Contains predicate on the "account_number" field.
func AccountNumberContains(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContains(FieldAccountNumber, v))
}

// AccountNumberHasPrefix applies the HasPrefix predicate on the "account_number" field.
func AccountNumberHasPrefix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasPrefix(FieldAccountNumber, v))
}

// AccountNumberHasSuffix applies the HasSuffix predicate on the "account_number" field.
func AccountNumberHasSuffix(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldHasSuffix(FieldAccountNumber, v))
}

// AccountNumberIsNil applies the IsNil predicate on the "account_number" field.
func AccountNumberIsNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldIsNull(FieldAccountNumber))
}

// AccountNumberNotNil applies the NotNil predicate on the "account_number" field.
func AccountNumberNotNil() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldNotNull(FieldAccountNumber))
}

// AccountNumberEqualFold applies the EqualFold predicate on the "account_number" field.
func AccountNumberEqualFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldEqualFold(FieldAccountNumber, v))
}

// AccountNumberContainsFold applies the ContainsFold predicate on the "account_number" field.
func AccountNumberContainsFold(v string) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.FieldContainsFold(FieldAccountNumber, v))
}

// HasGym applies the HasEdge predicate on the "gym" edge.
func HasGym() predicate.PaymentRequisite {
	return predicate.PaymentRequisite(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, GymTable, GymColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGymWith applies the HasEdge predicate on the "gym" edge with a given conditions (other predicates).
func HasGymWith(preds ...predicate.Gym) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(func(s *sql.Selector) {
		step := newGymStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentRequisite) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentRequisite) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentRequisite) predicate.PaymentRequisite {
	return predicate.PaymentRequisite(sql.NotPredicates(p))
}
