// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gym-api/ent/gym"
	"gym-api/ent/managerrole"
	"gym-api/ent/predicate"
	"gym-api/ent/user"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ManagerRoleQuery is the builder for querying ManagerRole entities.
type ManagerRoleQuery struct {
	config
	ctx        *QueryContext
	order      []managerrole.OrderOption
	inters     []Interceptor
	predicates []predicate.ManagerRole
	withGym    *GymQuery
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ManagerRoleQuery builder.
func (mrq *ManagerRoleQuery) Where(ps ...predicate.ManagerRole) *ManagerRoleQuery {
	mrq.predicates = append(mrq.predicates, ps...)
	return mrq
}

// Limit the number of records to be returned by this query.
func (mrq *ManagerRoleQuery) Limit(limit int) *ManagerRoleQuery {
	mrq.ctx.Limit = &limit
	return mrq
}

// Offset to start from.
func (mrq *ManagerRoleQuery) Offset(offset int) *ManagerRoleQuery {
	mrq.ctx.Offset = &offset
	return mrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrq *ManagerRoleQuery) Unique(unique bool) *ManagerRoleQuery {
	mrq.ctx.Unique = &unique
	return mrq
}

// Order specifies how the records should be ordered.
func (mrq *ManagerRoleQuery) Order(o ...managerrole.OrderOption) *ManagerRoleQuery {
	mrq.order = append(mrq.order, o...)
	return mrq
}

// QueryGym chains the current query on the "gym" edge.
func (mrq *ManagerRoleQuery) QueryGym() *GymQuery {
	query := (&GymClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managerrole.Table, managerrole.FieldID, selector),
			sqlgraph.To(gym.Table, gym.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, managerrole.GymTable, managerrole.GymColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (mrq *ManagerRoleQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(managerrole.Table, managerrole.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, managerrole.UserTable, managerrole.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ManagerRole entity from the query.
// Returns a *NotFoundError when no ManagerRole was found.
func (mrq *ManagerRoleQuery) First(ctx context.Context) (*ManagerRole, error) {
	nodes, err := mrq.Limit(1).All(setContextOp(ctx, mrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{managerrole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrq *ManagerRoleQuery) FirstX(ctx context.Context) *ManagerRole {
	node, err := mrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ManagerRole ID from the query.
// Returns a *NotFoundError when no ManagerRole ID was found.
func (mrq *ManagerRoleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(1).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{managerrole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrq *ManagerRoleQuery) FirstIDX(ctx context.Context) int {
	id, err := mrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ManagerRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ManagerRole entity is found.
// Returns a *NotFoundError when no ManagerRole entities are found.
func (mrq *ManagerRoleQuery) Only(ctx context.Context) (*ManagerRole, error) {
	nodes, err := mrq.Limit(2).All(setContextOp(ctx, mrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{managerrole.Label}
	default:
		return nil, &NotSingularError{managerrole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrq *ManagerRoleQuery) OnlyX(ctx context.Context) *ManagerRole {
	node, err := mrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ManagerRole ID in the query.
// Returns a *NotSingularError when more than one ManagerRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrq *ManagerRoleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(2).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{managerrole.Label}
	default:
		err = &NotSingularError{managerrole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrq *ManagerRoleQuery) OnlyIDX(ctx context.Context) int {
	id, err := mrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ManagerRoles.
func (mrq *ManagerRoleQuery) All(ctx context.Context) ([]*ManagerRole, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryAll)
	if err := mrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ManagerRole, *ManagerRoleQuery]()
	return withInterceptors[[]*ManagerRole](ctx, mrq, qr, mrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrq *ManagerRoleQuery) AllX(ctx context.Context) []*ManagerRole {
	nodes, err := mrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ManagerRole IDs.
func (mrq *ManagerRoleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mrq.ctx.Unique == nil && mrq.path != nil {
		mrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryIDs)
	if err = mrq.Select(managerrole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrq *ManagerRoleQuery) IDsX(ctx context.Context) []int {
	ids, err := mrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrq *ManagerRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryCount)
	if err := mrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrq, querierCount[*ManagerRoleQuery](), mrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrq *ManagerRoleQuery) CountX(ctx context.Context) int {
	count, err := mrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrq *ManagerRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryExist)
	switch _, err := mrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrq *ManagerRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := mrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ManagerRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrq *ManagerRoleQuery) Clone() *ManagerRoleQuery {
	if mrq == nil {
		return nil
	}
	return &ManagerRoleQuery{
		config:     mrq.config,
		ctx:        mrq.ctx.Clone(),
		order:      append([]managerrole.OrderOption{}, mrq.order...),
		inters:     append([]Interceptor{}, mrq.inters...),
		predicates: append([]predicate.ManagerRole{}, mrq.predicates...),
		withGym:    mrq.withGym.Clone(),
		withUser:   mrq.withUser.Clone(),
		// clone intermediate query.
		sql:  mrq.sql.Clone(),
		path: mrq.path,
	}
}

// WithGym tells the query-builder to eager-load the nodes that are connected to
// the "gym" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *ManagerRoleQuery) WithGym(opts ...func(*GymQuery)) *ManagerRoleQuery {
	query := (&GymClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withGym = query
	return mrq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *ManagerRoleQuery) WithUser(opts ...func(*UserQuery)) *ManagerRoleQuery {
	query := (&UserClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withUser = query
	return mrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ManagerRole managerrole.ManagerRole `json:"manager_role,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ManagerRole.Query().
//		GroupBy(managerrole.FieldManagerRole).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrq *ManagerRoleQuery) GroupBy(field string, fields ...string) *ManagerRoleGroupBy {
	mrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ManagerRoleGroupBy{build: mrq}
	grbuild.flds = &mrq.ctx.Fields
	grbuild.label = managerrole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ManagerRole managerrole.ManagerRole `json:"manager_role,omitempty"`
//	}
//
//	client.ManagerRole.Query().
//		Select(managerrole.FieldManagerRole).
//		Scan(ctx, &v)
func (mrq *ManagerRoleQuery) Select(fields ...string) *ManagerRoleSelect {
	mrq.ctx.Fields = append(mrq.ctx.Fields, fields...)
	sbuild := &ManagerRoleSelect{ManagerRoleQuery: mrq}
	sbuild.label = managerrole.Label
	sbuild.flds, sbuild.scan = &mrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ManagerRoleSelect configured with the given aggregations.
func (mrq *ManagerRoleQuery) Aggregate(fns ...AggregateFunc) *ManagerRoleSelect {
	return mrq.Select().Aggregate(fns...)
}

func (mrq *ManagerRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrq.ctx.Fields {
		if !managerrole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrq.path != nil {
		prev, err := mrq.path(ctx)
		if err != nil {
			return err
		}
		mrq.sql = prev
	}
	return nil
}

func (mrq *ManagerRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ManagerRole, error) {
	var (
		nodes       = []*ManagerRole{}
		withFKs     = mrq.withFKs
		_spec       = mrq.querySpec()
		loadedTypes = [2]bool{
			mrq.withGym != nil,
			mrq.withUser != nil,
		}
	)
	if mrq.withGym != nil || mrq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, managerrole.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ManagerRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ManagerRole{config: mrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mrq.withGym; query != nil {
		if err := mrq.loadGym(ctx, query, nodes, nil,
			func(n *ManagerRole, e *Gym) { n.Edges.Gym = e }); err != nil {
			return nil, err
		}
	}
	if query := mrq.withUser; query != nil {
		if err := mrq.loadUser(ctx, query, nodes, nil,
			func(n *ManagerRole, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mrq *ManagerRoleQuery) loadGym(ctx context.Context, query *GymQuery, nodes []*ManagerRole, init func(*ManagerRole), assign func(*ManagerRole, *Gym)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ManagerRole)
	for i := range nodes {
		if nodes[i].manager_role_gym == nil {
			continue
		}
		fk := *nodes[i].manager_role_gym
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(gym.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "manager_role_gym" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mrq *ManagerRoleQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ManagerRole, init func(*ManagerRole), assign func(*ManagerRole, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ManagerRole)
	for i := range nodes {
		if nodes[i].manager_role_user == nil {
			continue
		}
		fk := *nodes[i].manager_role_user
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "manager_role_user" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mrq *ManagerRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrq.querySpec()
	_spec.Node.Columns = mrq.ctx.Fields
	if len(mrq.ctx.Fields) > 0 {
		_spec.Unique = mrq.ctx.Unique != nil && *mrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrq.driver, _spec)
}

func (mrq *ManagerRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(managerrole.Table, managerrole.Columns, sqlgraph.NewFieldSpec(managerrole.FieldID, field.TypeInt))
	_spec.From = mrq.sql
	if unique := mrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managerrole.FieldID)
		for i := range fields {
			if fields[i] != managerrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrq *ManagerRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrq.driver.Dialect())
	t1 := builder.Table(managerrole.Table)
	columns := mrq.ctx.Fields
	if len(columns) == 0 {
		columns = managerrole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrq.sql != nil {
		selector = mrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrq.ctx.Unique != nil && *mrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrq.predicates {
		p(selector)
	}
	for _, p := range mrq.order {
		p(selector)
	}
	if offset := mrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ManagerRoleGroupBy is the group-by builder for ManagerRole entities.
type ManagerRoleGroupBy struct {
	selector
	build *ManagerRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrgb *ManagerRoleGroupBy) Aggregate(fns ...AggregateFunc) *ManagerRoleGroupBy {
	mrgb.fns = append(mrgb.fns, fns...)
	return mrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrgb *ManagerRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrgb.build.ctx, ent.OpQueryGroupBy)
	if err := mrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ManagerRoleQuery, *ManagerRoleGroupBy](ctx, mrgb.build, mrgb, mrgb.build.inters, v)
}

func (mrgb *ManagerRoleGroupBy) sqlScan(ctx context.Context, root *ManagerRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrgb.fns))
	for _, fn := range mrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrgb.flds)+len(mrgb.fns))
		for _, f := range *mrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ManagerRoleSelect is the builder for selecting fields of ManagerRole entities.
type ManagerRoleSelect struct {
	*ManagerRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrs *ManagerRoleSelect) Aggregate(fns ...AggregateFunc) *ManagerRoleSelect {
	mrs.fns = append(mrs.fns, fns...)
	return mrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrs *ManagerRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrs.ctx, ent.OpQuerySelect)
	if err := mrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ManagerRoleQuery, *ManagerRoleSelect](ctx, mrs.ManagerRoleQuery, mrs, mrs.inters, v)
}

func (mrs *ManagerRoleSelect) sqlScan(ctx context.Context, root *ManagerRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrs.fns))
	for _, fn := range mrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
