// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gym-api/ent/abonement"
	"gym-api/ent/payment"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Payment is the model entity for the Payment schema.
type Payment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// LinkPhoto holds the value of the "link_photo" field.
	LinkPhoto string `json:"link_photo,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ConfirmedAt holds the value of the "confirmed_at" field.
	ConfirmedAt time.Time `json:"confirmed_at,omitempty"`
	// IsConfirmed holds the value of the "is_confirmed" field.
	IsConfirmed bool `json:"is_confirmed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentQuery when eager-loading is set.
	Edges             PaymentEdges `json:"edges"`
	payment_abonement *int
	selectValues      sql.SelectValues
}

// PaymentEdges holds the relations/edges for other nodes in the graph.
type PaymentEdges struct {
	// Abonement holds the value of the abonement edge.
	Abonement *Abonement `json:"abonement,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AbonementOrErr returns the Abonement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentEdges) AbonementOrErr() (*Abonement, error) {
	if e.Abonement != nil {
		return e.Abonement, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: abonement.Label}
	}
	return nil, &NotLoadedError{edge: "abonement"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Payment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case payment.FieldIsConfirmed:
			values[i] = new(sql.NullBool)
		case payment.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case payment.FieldID:
			values[i] = new(sql.NullInt64)
		case payment.FieldLinkPhoto:
			values[i] = new(sql.NullString)
		case payment.FieldCreatedAt, payment.FieldConfirmedAt:
			values[i] = new(sql.NullTime)
		case payment.ForeignKeys[0]: // payment_abonement
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Payment fields.
func (pa *Payment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case payment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pa.ID = int(value.Int64)
		case payment.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				pa.Amount = value.Float64
			}
		case payment.FieldLinkPhoto:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link_photo", values[i])
			} else if value.Valid {
				pa.LinkPhoto = value.String
			}
		case payment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pa.CreatedAt = value.Time
			}
		case payment.FieldConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_at", values[i])
			} else if value.Valid {
				pa.ConfirmedAt = value.Time
			}
		case payment.FieldIsConfirmed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_confirmed", values[i])
			} else if value.Valid {
				pa.IsConfirmed = value.Bool
			}
		case payment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field payment_abonement", value)
			} else if value.Valid {
				pa.payment_abonement = new(int)
				*pa.payment_abonement = int(value.Int64)
			}
		default:
			pa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Payment.
// This includes values selected through modifiers, order, etc.
func (pa *Payment) Value(name string) (ent.Value, error) {
	return pa.selectValues.Get(name)
}

// QueryAbonement queries the "abonement" edge of the Payment entity.
func (pa *Payment) QueryAbonement() *AbonementQuery {
	return NewPaymentClient(pa.config).QueryAbonement(pa)
}

// Update returns a builder for updating this Payment.
// Note that you need to call Payment.Unwrap() before calling this method if this Payment
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Payment) Update() *PaymentUpdateOne {
	return NewPaymentClient(pa.config).UpdateOne(pa)
}

// Unwrap unwraps the Payment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pa *Payment) Unwrap() *Payment {
	_tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Payment is not a transactional entity")
	}
	pa.config.driver = _tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Payment) String() string {
	var builder strings.Builder
	builder.WriteString("Payment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pa.ID))
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", pa.Amount))
	builder.WriteString(", ")
	builder.WriteString("link_photo=")
	builder.WriteString(pa.LinkPhoto)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("confirmed_at=")
	builder.WriteString(pa.ConfirmedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_confirmed=")
	builder.WriteString(fmt.Sprintf("%v", pa.IsConfirmed))
	builder.WriteByte(')')
	return builder.String()
}

// Payments is a parsable slice of Payment.
type Payments []*Payment
