// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gym-api/ent/abonement"
	"gym-api/ent/abonementtype"
	"gym-api/ent/gym"
	"gym-api/ent/managerrole"
	"gym-api/ent/payment"
	"gym-api/ent/schema"
	"gym-api/ent/user"
	"gym-api/ent/userrole"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	abonementFields := schema.Abonement{}.Fields()
	_ = abonementFields
	// abonementDescPrice is the schema descriptor for price field.
	abonementDescPrice := abonementFields[1].Descriptor()
	// abonement.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	abonement.PriceValidator = abonementDescPrice.Validators[0].(func(float64) error)
	// abonementDescDurationMonths is the schema descriptor for duration_months field.
	abonementDescDurationMonths := abonementFields[2].Descriptor()
	// abonement.DefaultDurationMonths holds the default value on creation for the duration_months field.
	abonement.DefaultDurationMonths = abonementDescDurationMonths.Default.(int)
	// abonement.DurationMonthsValidator is a validator for the "duration_months" field. It is called by the builders before save.
	abonement.DurationMonthsValidator = abonementDescDurationMonths.Validators[0].(func(int) error)
	// abonementDescExpirationDate is the schema descriptor for expiration_date field.
	abonementDescExpirationDate := abonementFields[3].Descriptor()
	// abonement.DefaultExpirationDate holds the default value on creation for the expiration_date field.
	abonement.DefaultExpirationDate = abonementDescExpirationDate.Default.(func() time.Time)
	// abonementDescCreatedAt is the schema descriptor for created_at field.
	abonementDescCreatedAt := abonementFields[4].Descriptor()
	// abonement.DefaultCreatedAt holds the default value on creation for the created_at field.
	abonement.DefaultCreatedAt = abonementDescCreatedAt.Default.(func() time.Time)
	// abonementDescIsActive is the schema descriptor for is_active field.
	abonementDescIsActive := abonementFields[7].Descriptor()
	// abonement.DefaultIsActive holds the default value on creation for the is_active field.
	abonement.DefaultIsActive = abonementDescIsActive.Default.(bool)
	// abonementDescIsPaid is the schema descriptor for is_paid field.
	abonementDescIsPaid := abonementFields[8].Descriptor()
	// abonement.DefaultIsPaid holds the default value on creation for the is_paid field.
	abonement.DefaultIsPaid = abonementDescIsPaid.Default.(bool)
	abonementtypeFields := schema.AbonementType{}.Fields()
	_ = abonementtypeFields
	// abonementtypeDescCreatedAt is the schema descriptor for created_at field.
	abonementtypeDescCreatedAt := abonementtypeFields[1].Descriptor()
	// abonementtype.DefaultCreatedAt holds the default value on creation for the created_at field.
	abonementtype.DefaultCreatedAt = abonementtypeDescCreatedAt.Default.(func() time.Time)
	gymFields := schema.Gym{}.Fields()
	_ = gymFields
	// gymDescCurrencyID is the schema descriptor for currency_id field.
	gymDescCurrencyID := gymFields[1].Descriptor()
	// gym.DefaultCurrencyID holds the default value on creation for the currency_id field.
	gym.DefaultCurrencyID = gymDescCurrencyID.Default.(int)
	// gymDescCreatedAt is the schema descriptor for created_at field.
	gymDescCreatedAt := gymFields[7].Descriptor()
	// gym.DefaultCreatedAt holds the default value on creation for the created_at field.
	gym.DefaultCreatedAt = gymDescCreatedAt.Default.(func() time.Time)
	managerroleFields := schema.ManagerRole{}.Fields()
	_ = managerroleFields
	// managerroleDescCreatedAt is the schema descriptor for created_at field.
	managerroleDescCreatedAt := managerroleFields[1].Descriptor()
	// managerrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	managerrole.DefaultCreatedAt = managerroleDescCreatedAt.Default.(func() time.Time)
	// managerroleDescIsClose is the schema descriptor for is_close field.
	managerroleDescIsClose := managerroleFields[3].Descriptor()
	// managerrole.DefaultIsClose holds the default value on creation for the is_close field.
	managerrole.DefaultIsClose = managerroleDescIsClose.Default.(bool)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescCreatedAt is the schema descriptor for created_at field.
	paymentDescCreatedAt := paymentFields[2].Descriptor()
	// payment.DefaultCreatedAt holds the default value on creation for the created_at field.
	payment.DefaultCreatedAt = paymentDescCreatedAt.Default.(func() time.Time)
	// paymentDescIsConfirmed is the schema descriptor for is_confirmed field.
	paymentDescIsConfirmed := paymentFields[4].Descriptor()
	// payment.DefaultIsConfirmed holds the default value on creation for the is_confirmed field.
	payment.DefaultIsConfirmed = paymentDescIsConfirmed.Default.(bool)
	usagemodeFields := schema.UsageMode{}.Fields()
	_ = usagemodeFields
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescCreatedAt is the schema descriptor for created_at field.
	userroleDescCreatedAt := userroleFields[1].Descriptor()
	// userrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrole.DefaultCreatedAt = userroleDescCreatedAt.Default.(func() time.Time)
	// userroleDescIsClose is the schema descriptor for is_close field.
	userroleDescIsClose := userroleFields[3].Descriptor()
	// userrole.DefaultIsClose holds the default value on creation for the is_close field.
	userrole.DefaultIsClose = userroleDescIsClose.Default.(bool)
}
