// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gym-api/ent/predicate"
	"gym-api/ent/usagemode"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsageModeDelete is the builder for deleting a UsageMode entity.
type UsageModeDelete struct {
	config
	hooks    []Hook
	mutation *UsageModeMutation
}

// Where appends a list predicates to the UsageModeDelete builder.
func (umd *UsageModeDelete) Where(ps ...predicate.UsageMode) *UsageModeDelete {
	umd.mutation.Where(ps...)
	return umd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (umd *UsageModeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, umd.sqlExec, umd.mutation, umd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (umd *UsageModeDelete) ExecX(ctx context.Context) int {
	n, err := umd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (umd *UsageModeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usagemode.Table, sqlgraph.NewFieldSpec(usagemode.FieldID, field.TypeInt))
	if ps := umd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, umd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	umd.mutation.done = true
	return affected, err
}

// UsageModeDeleteOne is the builder for deleting a single UsageMode entity.
type UsageModeDeleteOne struct {
	umd *UsageModeDelete
}

// Where appends a list predicates to the UsageModeDelete builder.
func (umdo *UsageModeDeleteOne) Where(ps ...predicate.UsageMode) *UsageModeDeleteOne {
	umdo.umd.mutation.Where(ps...)
	return umdo
}

// Exec executes the deletion query.
func (umdo *UsageModeDeleteOne) Exec(ctx context.Context) error {
	n, err := umdo.umd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usagemode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (umdo *UsageModeDeleteOne) ExecX(ctx context.Context) {
	if err := umdo.Exec(ctx); err != nil {
		panic(err)
	}
}
